### ISSUE TITLE
Problem running on GPU machine

### ISSUE THREAD

**Issue by jpsember** [jpsember/java-ml#51]
```
example_yolo} *** WARNING (js_model.py   30): Enabling 'detect_anomaly'
(eioml) example_yolo} Traceback (most recent call last):
  File "../main_yolo.py", line 8, in <module>
    c.run_training_session()
  File "/home/eio/js_dep/ml/pycore/js_train.py", line 391, in run_training_session
    self.train()
  File "/home/eio/js_dep/ml/pycore/js_train.py", line 314, in train
    pred = self.model(tensor_images)
  File "/home/eio/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/eio/js_dep/ml/pycore/js_model.py", line 115, in forward
    return self.layers(x)
  File "/home/eio/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/eio/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/eio/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/eio/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/eio/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 444, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
(eioml) example_yolo} 
```

**Comment by jpsember** [comment]
https://stackoverflow.com/questions/59013109/

> You get this error because your model is on the GPU, but your data is on the CPU. So, you need to send your input tensors to the GPU.
