### ISSUE TITLE
Add inference capability in Python code

### ISSUE THREAD

**Issue by jpsember** [jpsember/java-ml#67]

**Comment by jpsember** [comment]
- [x] Add Java support for generating binary file of images to be processed by python

**Comment by jpsember** [comment]
Tried running on eioml, some sort of problem:
```
=============================================================================================================================
js_dep/ml/pycore/base.py (524)         : oper_info["fn"]()
../driver.py (57)                      : c.run_inference()
js_dep/ml/pycore/js_inference.py (114) : self.restore_checkpoint()
js_dep/ml/pycore/js_inference.py (167) : self.optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
***
*** 'YoloInference' object has no attribute 'optimizer'
Interpreting results
Exception in thread "main" java.lang.IllegalArgumentException: No such file: inference/results.bin context: (none)
	at js.base.Tools.badArgWithCause(Tools.java:468)
	at js.base.Tools.badArg(Tools.java:464)
	at js.file.Files.assertExists(Files.java:129)
	at js.file.Files.assertExists(Files.java:123)
	at ml.CompileImagesOper.processInferenceResult(CompileImagesOper.java:162)
	at ml.CompileImagesOper.performSubOperation(CompileImagesOper.java:89)
	at ml.CompileImagesOper.perform(CompileImagesOper.java:69)
	at js.app.App.auxRunOper(App.java:114)
	at js.app.App.runApplication(App.java:105)
	at js.app.App.startApplication(App.java:74)
	at ml.Main.main(Main.java:17)
(eioml) example_yolo} ls inference
total 16228
-rw-rw-r-- 1 eio eio 16613376 Jul 22 14:29 images.bin
-rw-rw-r-- 1 eio eio       94 Jul 22 14:29 image_set_info.json
(eioml) example_yolo} 
```
